# Generated by Django 4.2.7 on 2023-11-07 11:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0002_category_folder"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
